# Generated by Django 5.1.3 on 2024-11-26 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoreClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=5)),
                ("code", models.IntegerField()),
                ("credits", models.IntegerField()),
                ("pre_requisites", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Diploma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("graduation_date", models.DateField(blank=True, null=True)),
                ("GPA", models.FloatField(blank=True, null=True)),
                ("GPA2", models.FloatField(blank=True, null=True)),
                ("hours_attempted", models.IntegerField(blank=True, null=True)),
                ("hours_completed", models.IntegerField(blank=True, null=True)),
                ("classes_attempted", models.JSONField(blank=True, null=True)),
                ("classes_completed", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("max_hours_allowed", models.IntegerField(default=20)),
                ("registered_for", models.JSONField(blank=True, null=True)),
                ("in_progress", models.JSONField(blank=True, null=True)),
                ("gpa", models.FloatField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ElectiveClass",
            fields=[
                (
                    "coreclass_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="diploma.coreclass",
                    ),
                ),
                ("is_elective", models.BooleanField(default=True)),
            ],
            bases=("diploma.coreclass",),
        ),
        migrations.CreateModel(
            name="SpecialistClass",
            fields=[
                (
                    "coreclass_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="diploma.coreclass",
                    ),
                ),
            ],
            bases=("diploma.coreclass",),
        ),
        migrations.CreateModel(
            name="StudentDiploma",
            fields=[
                (
                    "diploma_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="diploma.diploma",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="my_diploma",
                        to="students.student",
                    ),
                ),
            ],
            bases=("diploma.diploma",),
        ),
        migrations.CreateModel(
            name="StudentTerm",
            fields=[
                (
                    "term_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="diploma.term",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="my_terms",
                        to="students.student",
                    ),
                ),
            ],
            bases=("diploma.term",),
        ),
    ]
