# Generated by Django 5.1.3 on 2024-12-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diploma", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coreclass",
            name="class_type",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
