# Generated by Django 5.1.3 on 2024-11-22 15:25

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("gpa", models.FloatField(default=0)),
                ("classification", models.CharField(max_length=12)),
                ("is_test_entry", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Student",
                "ordering": ("last_name", "first_name"),
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("degree", models.CharField(max_length=12)),
                ("university", models.CharField(blank=True, max_length=100, null=True)),
                ("is_test_entry", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Student",
                "ordering": ("last_name", "first_name"),
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
