# Generated by Django 5.1.3 on 2024-12-03 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="student_id",
        ),
        migrations.RemoveField(
            model_name="classroomstudent",
            name="gpa",
        ),
        migrations.RemoveField(
            model_name="grade",
            name="content_id",
        ),
        migrations.RemoveField(
            model_name="grade",
            name="grade",
        ),
        migrations.RemoveField(
            model_name="grade",
            name="student_id",
        ),
        migrations.RemoveField(
            model_name="quizam",
            name="student_id",
        ),
        migrations.AddField(
            model_name="assignment",
            name="date_completed",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assignment",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assignment",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assignment",
            name="points_available",
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name="classroom",
            name="class_number",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="classroom",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="classroom",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="classroom",
            name="max_seats",
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="classroom",
            name="required_materials",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="classroom",
            name="seats_taken",
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="classroom",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="classroom",
            name="students",
            field=models.ManyToManyField(
                related_name="classrooms",
                through="classroom.ClassroomStudent",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="teachers",
            field=models.ManyToManyField(
                related_name="classrooms",
                through="classroom.ClassroomTeacher",
                to="students.teacher",
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="grade",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grade",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="my_grades",
                to="classroom.classroomstudent",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="weighted_available",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="grade",
            name="weighted_points",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="quizam",
            name="date_completed",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quizam",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quizam",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quizam",
            name="points_available",
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="class_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="classroomstudent",
            name="classroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classroom_students",
                to="classroom.classroom",
            ),
        ),
        migrations.AlterField(
            model_name="classroomteacher",
            name="classroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classroom_teachers",
                to="classroom.classroom",
            ),
        ),
        migrations.CreateModel(
            name="CompletedAssignment",
            fields=[
                (
                    "assignment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="classroom.assignment",
                    ),
                ),
                (
                    "points_scored",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "assignment_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="classroom.assignment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completed_assignments",
                        to="classroom.classroomstudent",
                    ),
                ),
            ],
            bases=("classroom.assignment",),
        ),
        migrations.CreateModel(
            name="CompletedQuizam",
            fields=[
                (
                    "quizam_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="classroom.quizam",
                    ),
                ),
                (
                    "points_scored",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "quiz_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="classroom.quizam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completed_quizzes",
                        to="classroom.classroomstudent",
                    ),
                ),
            ],
            bases=("classroom.quizam",),
        ),
    ]
